name: Site Auditor (RD-PWA Beta)
on:
  push:
    branches:
      - rdpwa-beta
  pull_request:
    branches:
      - rdpwa-beta
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Live Site
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://beta-schedules.unisontech.org'
    - name: Upload Results as Artifact
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse Report (RD-PWA Beta)
        path: './report'
